project:  
  type: website
  render: 
    - "*.qmd"
    - "!2021/*"
    - "!2122/*"
  output-dir: ../docs/2223/labs

website:
  title: "DAPR2"
  page-footer: © Copyright 2019-2022 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.
  navbar:
    left:
    - text: "Intro to Linear Models"
      menu:
        - text: "1/1: Functions and Models"
          href: 1_01_function.html
        - text: "1/2: Intro to Linear Regression"
          href: 1_02_slr.html 
        - text: "1/3: Multiple Regression"
          href: 1_03_mlr.html
        - text: "1/4: Model Fit and Standardization"
          href: 1_04_model_fit.html
        - text: "1/5: Cat Predictors & Recap"
          href: 1_05_cat_recap.html
          
    - text: "More Linear Models"
      menu:
        - text: "1/7: Interactions I: Num x Cat"
          href: 1_07_int1_nc.html
        - text: "1/8: Interactions II: Num x Num"
          href: 1_08_int2_nn.html
        - text: "1/9: Interactions III: Cat x  Cat"
          href: 1_09_int3_cc.html
        - text: "1/10: Assumptions & Diagnostics"
          href: 1_10_assump_diag.html
        - text: "1/11: Write Up & Recap"
          href: 1_11_writeup_recap.html

    - text: "Analysing Experimental Studies"
      menu:
        - text: "2/1: Model Comparison"
          #href: 2_01_model_comps.html
        - text: "2/2: Effects Coding"
          #href: 2_02_effects.html
        - text: "2/3: Contrasts"
          #href: 2_03_contrasts.html
        - text: "2/4: Simple Effects & Pairwise Comparisons"
          #href: 2_04_emmeans.html
        - text: "2/5: Write Up & Recap"
          #href: 2_05_writeup_recap.html
          
    - text: "Advanced Topics for LM"
      menu:
        - text: "2/6: Binary Logistic Regression"
          #href: 
        - text: "2/7: More Logistic Regression"
          #href: 
        - text: "2/8: Sample Size & Power Analysis"
          #href: 
        - text: "2/9: Write Up & Recap"
          #href: 
        - text: "2/10: Mock Exam"
          #href: 
          
bibliography: biblio.bib

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/styles.scss
    include-in-header: "assets/toggling.html"
    number-sections: false
    code-copy: false
    code-link: true
 