project:  
  type: website
  render: 
    - "*.qmd"
    - "!archive_2021/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
  output-dir: ../docs/2324/labs

website:
  title: "DAPR2"
  page-footer: © Copyright 2019-2023 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.
  navbar:
    left:
    - text: "CSS TEST"
      href: csstests.html
    - text: "Intro to Linear Models"
      menu:
        - text: "1/1: Intro to Linear Regression"
          #href: 1_01_slr.html
        - text: "1/2: Multiple Regression"
          #href: 1_02_mlr.html 
        - text: "1/3: Multiple Regression & Standardization"
          #href: 1_03_mlr_stz.html
        - text: "1/4: Model Fit & Model Comparison"
          #href: 1_04_model_fit_comp.html
        - text: "1/5: Write Up & Block 1 Recap"
          #href: 1_05_writeup_recap.html
          
    - text: "More Linear Models"
      menu:
        - text: "1/7: Interactions I: Num x Cat"
          #href: 1_07_int1_nc.html
        - text: "1/8: Interactions II: Num x Num"
          #href: 1_08_int2_nn.html
        - text: "1/9: Interactions III: Cat x  Cat"
          #href: 1_09_int3_cc.html
        - text: "1/10: Assumptions & Diagnostics"
          #href: 1_10_assump_diag.html
        - text: "1/11: Write Up & Recap"
          #href: 1_11_writeup_recap.html

    - text: "Analysing Experimental Studies"
      menu:
        - text: "2/1: Model Comparison"
          #href: 2_01_model_comps.html
        - text: "2/2: Effects Coding"
          #href: 2_02_effects.html
        - text: "2/3: Contrasts"
          #href: 2_03_contrasts.html
        - text: "2/4: Simple Effects & Pairwise Comparisons"
          #href: 2_04_emmeans.html
        - text: "2/5: Write Up & Recap"
          #href: 2_05_writeup_recap.html
          
    - text: "Advanced Topics for LM"
      menu:
        - text: "2/6: Binary Logistic Regression"
          #href: 2_06_glm1.html
        - text: "2/7: More Logistic Regression"
          #href: 2_07_glm2.html
        - text: "2/8: Write Up & Recap"
          #href: 2_08_writeup_recap.html 
        - text: "2/9: Sample Size & Power Analysis"
          #href: 2_09_power.html
        - text: "2/10: Mock Exam"
          #href: 
          
bibliography: biblio.bib

format:
  html:
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false
    code-copy: false
    code-link: true
 