project:  
  type: website
  render: 
    - "*.qmd"
    - "!archive_2021/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
  output-dir: ../docs/2324/labs

website:
  title: "DAPR2"
  page-footer: © Copyright 2019-2023 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents: 
        - section: "Semester 1"
          contents:   
          
            - section: "Intro to Linear Models"
              contents:
                - 1_01_slr.qmd
                - 1_02_mlr.qmd            
                - 1_03_mlr_stz.qmd
                - 1_04_model_fit_comp.qmd
                - 1_05_writeup_recap.qmd
                
            - section: "Analysing and Evaluating Experimental Studies"
              contents:      
              
                - 1_06_dummy.qmd
                - 1_07_effects.qmd           
                - 1_08_assump_diag.qmd
                - 1_09_bootstrap.qmd
                - 1_10_writeup_recap_blk2.qmd
                  
        - section: "Semester 2"
          contents:    
          
            - section: "Interaction Models"
              contents:
                - 2_01_int1_nc.qmd
                #- 2_02_int2_nn.qmd
                #- 2_03_int3_cc.qmd
                #- 2_04_simp_pair.qmd
                #- 2_05_writeup_recap.qmd
                  
            - section: "Advanced Topics for LM"
              contents:
                #- 2_06_glm1.qmd
                #- 2_07_glm2.qmd
                #- 2_08_writeup_recap.qmd
                #- 2_09_power.qmd
                #- 2_10_mock.qmd
                   
                  
                  
bibliography: biblio.bib

format:
  html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false
    code-copy: false
    code-link: true
 